In [ ]:
import numpy as np

# Criando Matrizes Com Numpy
- Execute a célula 1 para importar a biblioteca necessária
- Garanta que você instalou a biblioteca no seu ambiente de desenvolviemnto para que a célula 1 funcione!
- Caso esteja em um ambiente de desenvolvimento online que não seja um VPS(Vitual Private Server) desconfigurado, não precisa se preocupar com isso.
  - Para conhecer ambiente de execução online acesse:
    - https://jupyter.org/
    - https://colab.research.google.com/

In [ ]:
#Criando matriz booleana de ordem 3 com todos os elementos da última coluna iguais à 1:
A = np.array([
  [0,0,1],
  [0,0,1],
  [0,0,1]
  ])

#Criando a mesma matriz utilizando conversão de quaisquer tipo de dados dentro dela para booleano:
Ab = np.array([
    [len([]), 0, 0.9],
    [0, None, 'g'],
    ['', False, np.NaN],],
    dtype=bool
    )

#Criando uma matriz não booleana 3x2:
B = np.array([[3, 7],
              [0, 1],
              [4, 4]])

#Criando uma matriz 3x2 de strings:
Bb = np.array([['a', 'b'],
               ['4', '7'],
               ['¬', '→']],
              dtype = str
              )

In [ ]:
#Observe que ao tentarmos criar uma matriz de matrizes obtem-se um erro:
MatrizDeMatrizes = np.array(
      [[A,Ab]
     ,[B,Bb]],
      )

<ipython-input-32-d76d523349a5>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  MatrizDeMatrizes = np.array(


ValueError: ignored

In [ ]:
#Para iterar várias matrizes de orens diferentes crie uma lista de matrizes ou outra esturutra de dados auxiliar:
ListaDeMatrizes = [A,Ab,B,Bb]

for i in ListaDeMatrizes:
  print('\n')
  for x in i:
    print(x)

#Outra alternativa é torná-las matrizes de mesma ordem caso isso não comprometa seus resultados e depois uní-las:
MatrizDeMatrizes = np.array(
    [
        #Acessando apenas as 2 últimas colunas das matrizes A e Ab:
        [A[:, 1:],Ab[:, 1:]],
        [B, Bb]
    ]
)




[0 0 1]
[0 0 1]
[0 0 1]


[False False  True]
[False False  True]
[False False  True]


[3 7]
[0 1]
[4 4]


['a' 'b']
['4' '7']
['¬' '→']


array([[[['0', '1'],
         ['0', '1'],
         ['0', '1']],

        [['False', 'True'],
         ['False', 'True'],
         ['False', 'True']]],


       [[['3', '7'],
         ['0', '1'],
         ['4', '4']],

        [['a', 'b'],
         ['4', '7'],
         ['¬', '→']]]], dtype='<U21')

# Acessando Linhas, Colunas e Diagonal principal

In [ ]:
#Duas formas diferentes de se acessar o primeiro elemento da matriz:
print(Ab[0][0])
print(Ab.item(0))

#Duas formas diferentes de se acessar o último elemento da matriz:
print(Ab[2][2])
print(Ab.item(5))

#Passando os valores de dentro de uma matriz para uma lista
array1D = []
for linha in Ab:
  for j in linha:
    array1D.append(j)

#Criando um vetor com os valores da diagonal principal de Ab:
rows, columns = Ab.shape
diagIndices = np.diag_indices(rows, columns)

#Acessando diagonal principal:
print('\n\n\n')
for i in diagIndices[0]:
  print(Ab[i][i])

False
False
True
True




False
False
True
